spring.application.name=Hospital_Manage
spring.datasource.url=jdbc:postgresql://localhost:5432/hms
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update